# Generated by Django 5.1 on 2024-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.TextField()),
                ('avatar', models.TextField(blank=True, null=True, unique=True)),
                ('tags_user', models.JSONField(default=list)),
                ('saved_posts', models.JSONField(default=list)),
                ('dashboards', models.ManyToManyField(blank=True, related_name='users_boards', to='dashboards.board')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='following', to='users.user')),
            ],
        ),
    ]
