# Generated by Django 5.1 on 2024-09-08 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='users.user'),
        ),
        migrations.AddField(
            model_name='board',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='boards', to='posts.post'),
        ),
    ]
